[package]
name = "program_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
rand = "0.8.5"
fuzz_harness = { path = "../fuzz_harness" }