[package]
name = "fuzz_harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[lib]
name = "fuzz_harness"
path = "src/lib.rs"

[[bin]]
name = "fuzz_harness_bin"
path = "src/bin.rs"